name: Full API Tests + Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

jobs:
  full_test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Newman Reporter
      run: npm install -g newman newman-reporter-htmlextra

    - name: Checkout gh-pages branch
      run: |
        git fetch origin gh-pages
        git checkout gh-pages
        mkdir -p gh-pages
        cp -r * gh-pages/ || true
        git checkout main

    - name: Run All Tests
      run: python scripts/run_all_test.py

    - name: Generate updated index.html
      run: python scripts/generate_index.py

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: gh-pages
        publish_branch: gh-pages
        keep_files: true
